[2024-11-05T13:00:25.446+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-05T13:00:25.463+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_test_v1.test_api manual__2024-11-05T13:00:23.193578+00:00 [queued]>
[2024-11-05T13:00:25.474+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_test_v1.test_api manual__2024-11-05T13:00:23.193578+00:00 [queued]>
[2024-11-05T13:00:25.475+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-11-05T13:00:25.489+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): test_api> on 2024-11-05 13:00:23.193578+00:00
[2024-11-05T13:00:25.498+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'api_test_v1', 'test_api', 'manual__2024-11-05T13:00:23.193578+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/Weather_etl_dag.py', '--cfg-path', '/tmp/tmp55cn7emz']
[2024-11-05T13:00:25.501+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2988) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-05T13:00:25.501+0000] {standard_task_runner.py:105} INFO - Job 25: Subtask test_api
[2024-11-05T13:00:25.502+0000] {standard_task_runner.py:72} INFO - Started process 2989 to run task
[2024-11-05T13:00:25.550+0000] {task_command.py:467} INFO - Running <TaskInstance: api_test_v1.test_api manual__2024-11-05T13:00:23.193578+00:00 [running]> on host 68d32cd9cfe4
[2024-11-05T13:00:25.755+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Simo' AIRFLOW_CTX_DAG_ID='api_test_v1' AIRFLOW_CTX_TASK_ID='test_api' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T13:00:23.193578+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T13:00:23.193578+00:00'
[2024-11-05T13:00:25.756+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-05T13:00:25.766+0000] {logging_mixin.py:190} INFO - 2024-11-05 13:00:25.766591
[2024-11-05T13:00:25.767+0000] {logging_mixin.py:190} INFO - https://api.openweathermap.org/data/2.5/weather?lat=6.175108444784084&lon=49.111459997943115&appid=None
[2024-11-05T13:00:25.956+0000] {logging_mixin.py:190} INFO - {'cod': 401, 'message': 'Invalid API key. Please see https://openweathermap.org/faq#error401 for more info.'}
[2024-11-05T13:00:25.958+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-05T13:00:25.965+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-05T13:00:25.966+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=api_test_v1, task_id=test_api, run_id=manual__2024-11-05T13:00:23.193578+00:00, execution_date=20241105T130023, start_date=20241105T130025, end_date=20241105T130025
[2024-11-05T13:00:26.003+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-05T13:00:26.019+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-05T13:00:26.024+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
